### PR TITLE
Barryvdh unit test

### PR DESCRIPTION
**Pull request by barryvdh**

### CODE REVIEW

**Comment by damienwebdev** [comment]
```json
"require": {
        "magento/framework": "^102.0 || ^103.0"
    },
```

**Comment by damienwebdev** [comment]
It also looks like, from a cursory review of your imports, you have an undocumented dependency on `magento/store`.

**Comment by barryvdh** [comment]
Seems to work now, thanks!

**Comment by damienwebdev** [comment]
🥳 🎈 🎉🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Pull request merged**
